Repository alpaka-group/cupla, pull requests merged in 2019-01, with the labels that each got.

#83 fix `cuplaGetLastError`
  src/common.cpp
Labels: bug

#85 add `cuplaStreamQuery()`
  include/cupla/api/stream.hpp
  include/cupla/cudaToCupla/runtime.hpp
  src/stream.cpp
Labels: enhancement

#87 update documentation of `cuplaGetLastError`
  include/cupla/api/common.hpp
Labels: documentation

#86 implement `cuplaPeekAtLastError()`
  include/cupla/api/common.hpp
  src/common.cpp
Labels: refactoring

#84 add implementation for `cuplaGetErrorString`
  include/cupla_driver_types.hpp
  src/common.cpp
Labels: enhancement

#90 fix TBB backend activation
  include/cupla/types.hpp
Labels: bug

#88 version increase to 0.1.1
  CHANGELOG.md
  cuplaConfig.cmake
  include/cupla/version.hpp
Labels: documentation

#92 Travis: CMake 3.11.0
  .travis.yml
Labels: enhancement

#93 CI: switch from clang 3.5 to 4.0
  .travis.yml
Labels: refactoring

#94 CI: update CUDA from 7.5 to 8.0
  .travis.yml
Labels: refactoring

#95 update documentation
  INSTALL.md
  README.md
Labels: documentation

#97 alpaka backend: HIP
  cuplaConfig.cmake
  include/cupla/datatypes/uint.hpp
  include/cupla/types.hpp
  src/common.cpp
Labels: enhancement
