Repository alpaka-group/cupla, pull requests merged in 2019-05, with the labels that each got.

#110 Changes function to macro 'CUPLA_ADD_EXECUTABLE'.
  cmake/addExecutable.cmake
Labels: bug

#106 Move all accelerator-specific code to an inline namespace
  include/cuda_to_cupla.hpp
  include/cupla/api/common.hpp
  include/cupla/api/device.hpp
  include/cupla/api/event.hpp
  include/cupla/api/memory.hpp
  include/cupla/api/stream.hpp
  include/cupla/c/datatypes/cuplaArray.hpp
  include/cupla/c/datatypes/cuplaExtent.hpp
  include/cupla/c/datatypes/cuplaMemcpy3DParms.hpp
  include/cupla/c/datatypes/cuplaPitchedPtr.hpp
  include/cupla/c/datatypes/cuplaPos.hpp
  include/cupla/cudaToCupla/driverTypes.hpp
  include/cupla/datatypes/Array.hpp
  include/cupla/datatypes/dim3.hpp
  include/cupla/datatypes/uint.hpp
  include/cupla/defines.hpp
  include/cupla/kernel.hpp
  include/cupla/manager/Device.hpp
  include/cupla/manager/Driver.hpp
  include/cupla/manager/Event.hpp
  include/cupla/manager/Memory.hpp
  include/cupla/manager/Stream.hpp
  include/cupla/namespace.hpp
  include/cupla/traits/IsThreadSeqAcc.hpp
  include/cupla/types.hpp
  include/cupla_runtime.hpp
  src/common.cpp
  src/device.cpp
  src/event.cpp
  src/manager/Driver.cpp
  src/memory.cpp
  src/stream.cpp
Labels: enhancement

#104 C++11 and cupla target linking in cmake
  cmake/addExecutable.cmake
  cuplaConfig.cmake
  example/CUDASamples/asyncAPI/CMakeLists.txt
  example/CUDASamples/asyncAPI_tuned/CMakeLists.txt
  example/CUDASamples/matrixMul/CMakeLists.txt
  example/CUDASamples/vectorAdd/CMakeLists.txt
Labels: enhancement, question

#111 Describes how to pull subtree as generic git author.
  INSTALL.md
  README.md
Labels: documentation
