Repository alpaka-group/cupla, pull requests merged in 2019-10, with the labels that each got.

#107 Add GitLab CI Tests
  .gitlab-ci.yml
Labels: continuous integration

#123 execution runtime for CI tests
  .gitlab-ci.yml
Labels: continuous integration, enhancement

#129 update travis CMake to 3.15.4
  .travis.yml
Labels: continuous integration

#130 fix `config header` test
  test/system/config/test.sh
Labels: bug, continuous integration

#132 Clarify documentation of inclusion order
  doc/PortingGuide.md
Labels: bug, documentation
