Repository alpaka-group/cupla, pull requests merged in 2020-01, with the labels that each got.

#139 fix config header
  include/cupla/config/CpuOmp2Blocks.hpp
  include/cupla/config/CpuOmp2Threads.hpp
  include/cupla/config/CpuSerial.hpp
  include/cupla/config/CpuTbbBlocks.hpp
  include/cupla/config/CpuThreads.hpp
  include/cupla/config/GpuCudaRt.hpp
  include/cupla/config/GpuHipRt.hpp
Labels: bug

#137 support for alpaka OMP4 backend
  INSTALL.md
  include/cupla/config/CpuOmp4.hpp
  include/cupla/defines.hpp
  include/cupla/namespace.hpp
  include/cupla/types.hpp
Labels: enhancement

#136 refactor cupla kernel execution
  include/cupla/kernel.hpp
Labels: refactoring

#140 compile cupla interfaces into static cupla library
  cmake/addExecutable.cmake
  cuplaConfig.cmake
Labels: refactoring

#141 Extend comments of atomic functions
  include/cupla/cudaToCupla/driverTypes.hpp
Labels: documentation

#142 Fix warnings concerning type casting
  include/cupla/manager/Device.hpp
  src/event.cpp
Labels: warning

#144 pin memory allocated with `cuplaMallocHoast`
  src/memory.cpp
Labels: enhancement
