Repository alpaka-group/cupla, pull requests merged in 2020-06, with the labels that each got.

#175 Fixed URLs in INSTALL.md
  INSTALL.md
Labels: documentation

#177 Second try: Extends GitLab CI scripts to run different compiler versions
  .gitlab-ci.yml
  script/compiler_base.yml
  script/run_test.sh
Labels: testing/CI

#179 config headers: not require cupla renaming headers
  include/cupla/config/CpuOmp2Blocks.hpp
  include/cupla/config/CpuOmp2Threads.hpp
  include/cupla/config/CpuOmp4.hpp
  include/cupla/config/CpuSerial.hpp
  include/cupla/config/CpuTbbBlocks.hpp
  include/cupla/config/CpuThreads.hpp
  include/cupla/config/GpuCudaRt.hpp
  include/cupla/config/GpuHipRt.hpp
  test/system/config/kernel.cpp
  test/system/config/main.cpp
Labels: bug
