Repository alpaka-group/cupla, pull requests merged in 2020-05, with the labels that each got.

#168 refactor math functions
  example/CUDASamples/blackScholes/src/BlackScholes_gold.cpp
  include/cupla/cudaToCupla/runtime.hpp
  include/cupla/defines.hpp
  include/cupla/device/math/Common.hpp
Labels: refactoring

#170 Change docker images for GitLab CI tests
  .gitlab-ci.yml
  script/compiler_base.yml
  script/run_test.yml
Labels: testing/CI

#172 Fix ; warnings
  src/event.cpp
  src/memory.cpp
  src/stream.cpp
Labels: warning
