Repository alpaka-group/cupla, pull requests merged in 2020-02, with the labels that each got.

#148 add cupla logo
  README.md
  doc/logo/cupla_logo.svg
  doc/logo/cupla_logo_320x210.png
  doc/logo/cupla_logo_320x210_bw.png
  doc/logo/cupla_logo_bw.svg
Labels: documentation

#149 use CMake 3.11.4 for travis tests
  .travis.yml
Labels: continuous integration

#150 Extend the docs with thread unsafety
  doc/PortingGuide.md
Labels: documentation

#147 update author section
  README.md
Labels: documentation

#145 update minimal CMake requirements to 3.11.4
  INSTALL.md
  README.md
  cuplaConfig.cmake
  example/CUDASamples/asyncAPI/CMakeLists.txt
  example/CUDASamples/asyncAPI_tuned/CMakeLists.txt
  example/CUDASamples/matrixMul/CMakeLists.txt
  example/CUDASamples/vectorAdd/CMakeLists.txt
Labels: documentation

#146 changelog and version increase to 0.2.0
  CHANGELOG.md
  cuplaConfig.cmake
  include/cupla/version.hpp
Labels: documentation

#153 Add Black-Scholes example
  .travis.yml
  example/CUDASamples/blackScholes/CMakeLists.txt
  example/CUDASamples/blackScholes/doc/BlackScholes.pdf
  example/CUDASamples/blackScholes/readme.txt
  example/CUDASamples/blackScholes/src/BlackScholes.cpp
  example/CUDASamples/blackScholes/src/BlackScholes_gold.cpp
  example/CUDASamples/blackScholes/src/BlackScholes_kernel.cuh
Labels: example

#154 Adds float3 and int3 with make-functions.
  include/cupla/cudaToCupla/driverTypes.hpp
Labels: enhancement

#152 update release date for 0.2.0
  CHANGELOG.md
Labels: documentation

#159 fix `KernelWithElementLevel` documentation
  include/cupla/kernel.hpp
Labels: bug, documentation
