Repository alpaka-group/cupla, pull requests merged in 2021-07, with the labels that each got.

#202 CI: remove travis tests
  .travis.yml
  README.md
Labels: testing/CI

#201 Topic update to latest alpaka release 0.6.1
  README.md
  alpaka/.zenodo.json
  alpaka/CHANGELOG.md
  alpaka/example/openMPSchedule/src/openMPSchedule.cpp
  alpaka/include/alpaka/block/shared/st/detail/BlockSharedMemStMemberImpl.hpp
  alpaka/include/alpaka/kernel/TaskKernelOacc.hpp
  alpaka/test/unit/warp/src/Activemask.cpp
  alpaka/test/unit/warp/src/Ballot.cpp
Labels: enhancement

#207 Fix the header of the README.md
  .rodare.json
  README.md
Labels: documentation

#204 add badge for master
  README.md
Labels: documentation

#206 set version to 0.4.0-dev
  cuplaConfig.cmake
  include/cupla/version.hpp
Labels: documentation

#205 change version to 0.3.0-rc1
  include/cupla/version.hpp
Labels: documentation
